version: "3.10"
services:
  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    container_name: backend
    image: kubanez/foodcast_backend:v1.2
    volumes:
      - ./foodcast:/app
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  static_value:
  media_value:
