# Generated by Django 4.2.5 on 2023-09-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='SKU продукта')),
                ('uom', models.PositiveIntegerField(verbose_name='UOM еденица измерения')),
                ('group', models.CharField(max_length=40, verbose_name='Группа товаров')),
                ('category', models.CharField(max_length=40, verbose_name='Категория товаров')),
                ('subcategory', models.CharField(max_length=40, verbose_name='Подкатегория товаров')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('title', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Название')),
                ('city', models.CharField(max_length=60, verbose_name='Город')),
                ('division', models.CharField(max_length=60, verbose_name='Дивизион')),
                ('type_format', models.PositiveIntegerField(verbose_name='Тип Формата')),
                ('loc', models.PositiveIntegerField(verbose_name='Локация')),
                ('size', models.PositiveIntegerField(verbose_name='Размер')),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Магазин ТК',
                'verbose_name_plural': 'Магазины ТК',
                'ordering': ['title'],
            },
        ),
        migrations.AddConstraint(
            model_name='shops',
            constraint=models.UniqueConstraint(fields=('title',), name='unique title of shop'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku',), name='unique sku'),
        ),
    ]
