# Generated by Django 4.2.5 on 2023-09-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100, verbose_name="SKU продукта")),
                (
                    "uom",
                    models.CharField(
                        max_length=20, verbose_name="UOM еденица измерения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Категория товаров"),
                ),
            ],
            options={
                "verbose_name": "Категория товара",
                "verbose_name_plural": "Категории товаров",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Группа товаров"),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ProductSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Подкатегория товаров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория товара",
                "verbose_name_plural": "Подкатегории товаров",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Shops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("city", models.CharField(max_length=60, verbose_name="Город")),
                ("division", models.CharField(max_length=60, verbose_name="Дивизион")),
                (
                    "type_format",
                    models.PositiveIntegerField(verbose_name="Тип Формата"),
                ),
                ("loc", models.PositiveIntegerField(verbose_name="Локация")),
                ("size", models.PositiveIntegerField(verbose_name="Размер")),
                ("is_active", models.BooleanField()),
            ],
            options={
                "verbose_name": "Магазин ТК",
                "verbose_name_plural": "Магазины ТК",
                "ordering": ["title"],
            },
        ),
        migrations.AddConstraint(
            model_name="shops",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique title of shop"
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category",
                to="products.productcategory",
                verbose_name="Подкатегория товаров",
            ),
        ),
        migrations.AddConstraint(
            model_name="productgroup",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique sku group"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_group",
                to="products.productgroup",
                verbose_name="Категория группы товаров",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category",
                to="products.productcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_group",
                to="products.productgroup",
                verbose_name="Группа",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_subcategory",
                to="products.productsubcategory",
                verbose_name="Подкатегория",
            ),
        ),
        migrations.AddConstraint(
            model_name="productsubcategory",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique sku sub_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique sku category"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(fields=("sku",), name="unique sku"),
        ),
    ]
