# Generated by Django 4.2.5 on 2023-10-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forecast",
            name="sales_units",
        ),
        migrations.CreateModel(
            name="ForecastPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("value", models.PositiveIntegerField(verbose_name="Значение")),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_point",
                        to="products.forecast",
                        verbose_name="",
                    ),
                ),
            ],
        ),
    ]
