# Generated by Django 4.2.5 on 2023-10-01 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_datapoint_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='fact',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datapoint', to='products.sales', verbose_name='Реализация'),
            preserve_default=False,
        ),
    ]
