# Generated by Django 4.2.5 on 2023-09-27 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
